name: "transcriber"

on:
  workflow_dispatch:
    inputs:
      audioURL:
        description: "Audio file URL"
        required: true
        type: string
      whisperModel:
        description: "The model size for whisper, default is base.en. For more details, checkout https://github.com/openai/whisper#available-models-and-languages"
        default: "base.en"
        type: string
      targetLanguage:
        description: "The target language for translation, default is zh (Chinese)"
        default: "zh"
        type: string
      translate:
        description: "Whether translating the srt file"
        default: true
        type: boolean
      upload:
        description: "上传网址"
        default: "https://www.wkkc.vip/"
        type: string
      convert:
        description: "转化mp3网址"
        default: "https://audio-convert.com/cn"
        type: string
      

jobs:
  transcribe:
    name: "Transcribe"
    runs-on: ubuntu-latest
    container: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
    env:
      audioURL: ${{ inputs.audioURL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install packages
        run: apt update && apt install -y ffmpeg fonts-noto-cjk curl file
      - name: Download / convert audio file
        run: |
          mkdir -p workdir
          cd workdir
          echo "Downloading file..."
          filename=$(curl -sJOL ${audioURL} -w "%{filename_effective}")
          filename_base=${filename%.*}
          echo "filename=${filename}" >> $GITHUB_ENV
          echo "filename_base=${filename_base}" >> $GITHUB_ENV
          if [[ $(file -bi "$filename") == video/* ]]; then # Determine filetype
            echo "Detected input as a video file, converting to .wav..."
            ffmpeg -i "$filename" "$filename_base".wav
            is_video=true
            whisper_file="${filename_base}.wav"
          else
            is_video=false
            whisper_file="${filename}"
          fi
          echo "is_video=${is_video}" >> $GITHUB_ENV
          echo "whisper_file=${whisper_file}" >> $GITHUB_ENV
          echo "Downloaded file: ${filename}"
      - name: Transcribe!
        working-directory: ./workdir
        run: |
          export PATH="/usr/src/.venv/bin:$PATH"
          if [[ ${{ inputs.translate }} == true ]]; then
            /usr/src/.venv/bin/python /usr/src/src/main.py -d cpu -t -m ${{ inputs.whisperModel }} -tl ${{ inputs.targetLanguage }} ${{ env.whisper_file }}
          else
            /usr/src/.venv/bin/python /usr/src/src/main.py -d cpu -m ${{ inputs.whisperModel }} -tl ${{ inputs.targetLanguage }} ${{ env.whisper_file }}
          fi
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: workdir/
          name: ${{ env.filename_base }}
